### PR TITLE
Add command to compare configurations

### PR DESCRIPTION
**Pull request by Dekker1**
Adds the `compare-configurations` command that takes two configurations from the statistics files and show any significant changes between the two. For example:

```
Summary:
========
- Status Changes: 14 (positive: 6)
- Runtime Changes: 18 (positive: 10)
- Objective Changes: 1 (posxive: 1)


Status Changes:
===============

Negative Status Changes:
------------------------
OPTIMAL_SOLUTION -> SATISFIED:
  - data/mznc2020/skill-allocation/skill_allocation_only.mzn data/mznc2020/skill-allocation/skill_allocation_mzn_1m_1.dzn
SATISFIED -> UNKNOWN:
  - data/mznc2020/stable-goods/stable-goods-solution.mzn data/mznc2020/stable-goods/s-d6.dzn
  - data/mznc2019/median-string/median_string_dp.mzn data/mznc2019/median-string/p2_10_8-3.dzn
  - data/mznc2019/rotating-workforce/rotating-workforce.mzn data/mznc2019/rotating-workforce/Example789.dzn
  - data/mznc2020/skill-allocation/skill_allocation_only.mzn data/mznc2020/skill-allocation/skill_allocation_mzn_2m_3.dzn
OPTIMAL_SOLUTION -> UNKNOWN:
  - data/mznc2020/skill-allocation/skill_allocation_only.mzn data/mznc2020/skill-allocation/skill_allocation_mzn_2m_1.dzn
  - data/mznc2020/sdn-chain/model.mzn data/mznc2020/sdn-chain/d10n780-2.dzn
  - data/mznc2020/sdn-chain/model.mzn data/mznc2020/sdn-chain/d10n780-1.dzn

Positive Status Changes:
------------------------
UNKNOWN -> OPTIMAL_SOLUTION:
  - data/mznc2019/hrc/hrc.mzn data/mznc2019/hrc/exp1-1-5110.dzn
  - data/mznc2020/hoist-benchmark-for-minizinc/hoist-benchmark.mzn data/mznc2020/hoist-benchmark-for-minizinc/PU_2_8_1.dzn
ERROR -> UNKNOWN:
  - data/mznc2020/pentominoes/pentominoes-int.mzn data/mznc2020/pentominoes/04.dzn
SATISFIED -> OPTIMAL_SOLUTION:
  - data/mznc2020/racp/racp.mzn data/mznc2020/racp/j30_26_2_1.0.dzn
UNKNOWN -> SATISFIED:
  - data/mznc2020/cable_tree_wiring/ctw.mzn data/mznc2020/cable_tree_wiring/R046.dzn
  - data/mznc2020/tower_challenge/tower.mzn data/mznc2020/tower_challenge/tower_070_070_15_070-04.dzn

Timing Changes (>±10.0%):
=========================
- (205.2%: 14.2s -> 43.4s) data/mznc2019/zephyrus/zephyrus.mzn data/mznc2019/zephyrus/12__10__8__3.dzn
- (127.1%: 65.3s -> 148.4s) data/mznc2019/amaze/amaze3.mzn data/mznc2019/amaze/2012-03-29.dzn
- (112.4%: 7.5s -> 15.8s) data/mznc2019/zephyrus/zephyrus.mzn data/mznc2019/zephyrus/12__8__6__3.dzn
- (98.4%: 431.6s -> 856.3s) data/mznc2020/sdn-chain/model.mzn data/mznc2020/sdn-chain/d24n600-3.dzn
- (57.3%: 105.6s -> 166.1s) data/mznc2019/rotating-workforce/rotating-workforce.mzn data/mznc2019/rotating-workforce/Example1337.dzn
- (28.6%: 23.7s -> 30.5s) data/mznc2019/zephyrus/zephyrus.mzn data/mznc2019/zephyrus/14__6__6__3.dzn
- (23.7%: 30.0s -> 37.1s) data/mznc2019/zephyrus/zephyrus.mzn data/mznc2019/zephyrus/14__10__6__3.dzn
- (14.9%: 163.0s -> 187.3s) data/mznc2019/triangular/triangular.mzn data/mznc2019/triangular/n10.dzn
- (-13.8%: 18.5s -> 15.9s) data/mznc2019/zephyrus/zephyrus.mzn data/mznc2019/zephyrus/12__6__6__3.dzn
- (-17.5%: 1.6s -> 1.3s) data/mznc2019/ptv/pax_model.mzn data/mznc2019/ptv/pax_period_20_2b.dzn
- (-25.0%: 1.8s -> 1.4s) data/mznc2019/ptv/pax_model.mzn data/mznc2019/ptv/pax_period_20_5b.dzn
- (-25.3%: 97.5s -> 72.9s) data/mznc2019/hrc/hrc.mzn data/mznc2019/hrc/exp1-1-5460.dzn
- (-25.7%: 1.8s -> 1.4s) data/mznc2019/ptv/pax_model.mzn data/mznc2019/ptv/pax_period_20_3b.dzn
- (-53.9%: 946.1s -> 436.5s) data/mznc2020/hoist-benchmark-for-minizinc/hoist-benchmark.mzn data/mznc2020/hoist-benchmark-for-minizinc/PU_1_2_2.dzn
- (-60.7%: 366.0s -> 143.7s) data/mznc2019/ptv/pax_model.mzn data/mznc2019/ptv/pax_period_20_1c.dzn
- (-73.9%: 77.2s -> 20.1s) data/mznc2019/fox-geese-corn/foxgeesecorn.mzn data/mznc2019/fox-geese-corn/foxgeesecorn_54.dzn
- (-79.7%: 65.0s -> 13.2s) data/mznc2020/is/model.mzn data/mznc2020/is/v1HjuSBQMb.dzn
- (-81.0%: 584.1s -> 110.8s) data/mznc2019/hrc/hrc.mzn data/mznc2019/hrc/exp1-1-5425.dzn

Objective Changes (>±10.0%):
=========================
- (-14.9%: MIN 47.00 -> 40.00) data/mznc2020/minimal-decision-sets/sparse_mds.mzn data/mznc2020/minimal-decision-sets/backache_train4.dzn
```

### CODE REVIEW

**Comment by Dekker1** [comment]
This command should have some testing. (and maybe some feedback if there are missing features)

**Comment by glebbelov** [comment]
Can have acceptance testing for this so we can modify features safely. For example, providing 2 fake statistics and checking the number/kind of outputs. To facilitate checking, the output could be in YAML/TOML/JSON/etc

What about comparing multiple outputs and finding contradictions? To switch to this system, I'd need that.

**Comment by Dekker1** [comment]
I suppose my idea was that the `PerformanceChanges` object would be used directly if you want to further analyse the results. It would be possible to use this in any new scripts. The output was really only meant for human consumption, but we can also add a YAML/JSON/TOML output mode to the command

My current implementation already finds and report conflicting solving status's, but I haven't done anything yet for conflicting optimal objectives, which I probably should.

**Comment by Dekker1** [comment]
@glebbelov I've added the finding of conflicting objectives as well (which already proved quite useful on my current benchmark.

I'll see if I have time this weekend to add the serialised output mode

**Comment by Dekker1** [comment]
@glebbelov I've added a `--output-mode json` flag which will give you something like this:

```{
  "status_changes": [
    {
      "model": "data/mznc2020/skill-allocation/skill_allocation_only.mzn",
      "data": "data/mznc2020/skill-allocation/skill_allocation_mzn_1m_1.dzn",
      "status_before": "OPTIMAL_SOLUTION",
      "status_after": "SATISFIED"
    },
    {
      "model": "data/mznc2020/stable-goods/stable-goods-solution.mzn",
      "data": "data/mznc2020/stable-goods/s-d6.dzn",
      "status_before": "SATISFIED",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2019/median-string/median_string_dp.mzn",
      "data": "data/mznc2019/median-string/p2_10_8-3.dzn",
      "status_before": "SATISFIED",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2019/rotating-workforce/rotating-workforce.mzn",
      "data": "data/mznc2019/rotating-workforce/Example789.dzn",
      "status_before": "SATISFIED",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2020/skill-allocation/skill_allocation_only.mzn",
      "data": "data/mznc2020/skill-allocation/skill_allocation_mzn_2m_3.dzn",
      "status_before": "SATISFIED",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2019/hrc/hrc.mzn",
      "data": "data/mznc2019/hrc/exp1-1-5110.dzn",
      "status_before": "UNKNOWN",
      "status_after": "OPTIMAL_SOLUTION"
    },
    {
      "model": "data/mznc2020/hoist-benchmark-for-minizinc/hoist-benchmark.mzn",
      "data": "data/mznc2020/hoist-benchmark-for-minizinc/PU_2_8_1.dzn",
      "status_before": "UNKNOWN",
      "status_after": "OPTIMAL_SOLUTION"
    },
    {
      "model": "data/mznc2020/skill-allocation/skill_allocation_only.mzn",
      "data": "data/mznc2020/skill-allocation/skill_allocation_mzn_2m_1.dzn",
      "status_before": "OPTIMAL_SOLUTION",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2020/sdn-chain/model.mzn",
      "data": "data/mznc2020/sdn-chain/d10n780-2.dzn",
      "status_before": "OPTIMAL_SOLUTION",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2020/sdn-chain/model.mzn",
      "data": "data/mznc2020/sdn-chain/d10n780-1.dzn",
      "status_before": "OPTIMAL_SOLUTION",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2020/pentominoes/pentominoes-int.mzn",
      "data": "data/mznc2020/pentominoes/04.dzn",
      "status_before": "ERROR",
      "status_after": "UNKNOWN"
    },
    {
      "model": "data/mznc2020/racp/racp.mzn",
      "data": "data/mznc2020/racp/j30_26_2_1.0.dzn",
      "status_before": "SATISFIED",
      "status_after": "OPTIMAL_SOLUTION"
    },
    {
      "model": "data/mznc2020/cable_tree_wiring/ctw.mzn",
      "data": "data/mznc2020/cable_tree_wiring/R046.dzn",
      "status_before": "UNKNOWN",
      "status_after": "SATISFIED"
    },
    {
      "model": "data/mznc2020/tower_challenge/tower.mzn",
      "data": "data/mznc2020/tower_challenge/tower_070_070_15_070-04.dzn",
      "status_before": "UNKNOWN",
      "status_after": "SATISFIED"
    }
  ],
  "time_delta": 0.1,
  "time_changes": [
    {
      "model": "data/mznc2019/zephyrus/zephyrus.mzn",
      "data": "data/mznc2019/zephyrus/12__10__8__3.dzn",
      "time_before": 14.233256462961435,
      "time_after": 43.44532513990998
    },
    {
      "model": "data/mznc2019/ptv/pax_model.mzn",
      "data": "data/mznc2019/ptv/pax_period_20_2b.dzn",
      "time_before": 1.6056028865277767,
      "time_after": 1.3246357776224613
    },
    {
      "model": "data/mznc2019/ptv/pax_model.mzn",
      "data": "data/mznc2019/ptv/pax_period_20_1c.dzn",
      "time_before": 366.0079421028495,
      "time_after": 143.70719466730952
    },
    {
      "model": "data/mznc2019/zephyrus/zephyrus.mzn",
      "data": "data/mznc2019/zephyrus/12__6__6__3.dzn",
      "time_before": 18.500466357916594,
      "time_after": 15.946741975843906
    },
    {
      "model": "data/mznc2020/is/model.mzn",
      "data": "data/mznc2020/is/v1HjuSBQMb.dzn",
      "time_before": 65.0361775867641,
      "time_after": 13.202197145670652
    },
    {
      "model": "data/mznc2019/ptv/pax_model.mzn",
      "data": "data/mznc2019/ptv/pax_period_20_5b.dzn",
      "time_before": 1.8290655612945557,
      "time_after": 1.37178985029459
    },
    {
      "model": "data/mznc2019/amaze/amaze3.mzn",
      "data": "data/mznc2019/amaze/2012-03-29.dzn",
      "time_before": 65.34373217821121,
      "time_after": 148.4104983098805
    },
    {
      "model": "data/mznc2019/rotating-workforce/rotating-workforce.mzn",
      "data": "data/mznc2019/rotating-workforce/Example1337.dzn",
      "time_before": 105.59825354442,
      "time_after": 166.14923387393355
    },
    {
      "model": "data/mznc2020/hoist-benchmark-for-minizinc/hoist-benchmark.mzn",
      "data": "data/mznc2020/hoist-benchmark-for-minizinc/PU_1_2_2.dzn",
      "time_before": 946.1476475223899,
      "time_after": 436.4748261831701
    },
    {
      "model": "data/mznc2020/sdn-chain/model.mzn",
      "data": "data/mznc2020/sdn-chain/d24n600-3.dzn",
      "time_before": 431.6308573819697,
      "time_after": 856.3434832021594
    },
    {
      "model": "data/mznc2019/hrc/hrc.mzn",
      "data": "data/mznc2019/hrc/exp1-1-5460.dzn",
      "time_before": 97.5393690392375,
      "time_after": 72.89502796530724
    },
    {
      "model": "data/mznc2019/zephyrus/zephyrus.mzn",
      "data": "data/mznc2019/zephyrus/14__6__6__3.dzn",
      "time_before": 23.70475421845913,
      "time_after": 30.493509765714407
    },
    {
      "model": "data/mznc2019/zephyrus/zephyrus.mzn",
      "data": "data/mznc2019/zephyrus/12__8__6__3.dzn",
      "time_before": 7.455252263695002,
      "time_after": 15.835256159305573
    },
    {
      "model": "data/mznc2019/ptv/pax_model.mzn",
      "data": "data/mznc2019/ptv/pax_period_20_3b.dzn",
      "time_before": 1.8448514454066753,
      "time_after": 1.3706931211054325
    },
    {
      "model": "data/mznc2019/triangular/triangular.mzn",
      "data": "data/mznc2019/triangular/n10.dzn",
      "time_before": 163.01880019530654,
      "time_after": 187.2890826202929
    },
    {
      "model": "data/mznc2019/zephyrus/zephyrus.mzn",
      "data": "data/mznc2019/zephyrus/14__10__6__3.dzn",
      "time_before": 29.98905685171485,
      "time_after": 37.08809784427285
    }
  ],
  "obj_delta": 0.1,
  "obj_changes": [
    {
      "model": "data/mznc2020/minimal-decision-sets/sparse_mds.mzn",
      "data": "data/mznc2020/minimal-decision-sets/backache_train4.dzn",
      "obj_before": 47,
      "obj_after": 40,
      "maximise": false
    }
  ],
  "obj_conflicts": [
    {
      "model": "data/mznc2019/fox-geese-corn/foxgeesecorn.mzn",
      "data": "data/mznc2019/fox-geese-corn/foxgeesecorn_54.dzn",
      "obj_before": 1957,
      "obj_after": 1962
    },
    {
      "model": "data/mznc2019/hrc/hrc.mzn",
      "data": "data/mznc2019/hrc/exp1-1-5425.dzn",
      "obj_before": 9,
      "obj_after": 8
    }
  ],
  "missing_instances": []
}```

Was there anything else that you were hoping to get out of the comparison?

**Review by cyderize — APPROVED** [review]

**Pull request merged**
